sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --install-ghc build
- stack exec hendleyhardgoods clean
- stack exec hendleyhardgoods build
cache:
  directories:
  - "$HOME/.stack"
deploy:
  provider: s3
  access_key_id: AKIAJOPJPECIU2VKXQIA
  bucket: hendleyhardgoods.com
  local-dir: build
  acl: public_read
  region: us-west-1
  skip_cleanup: true
  on:
    repo: schell/hendleyhardgoods
    branch: master
  secret_access_key:
    secure: E0HoXZdtzrEcwAdHl93G3a2PvSnjmNvltsMc//owFK82E05HeHuo0tQdAE8puA61PPKDcvuSXAM0I3x353DxDLoW5A+p7l6vVctEoaOR3I7PW98G0SsvZsypsizDH5dGUOfAdaM2IdgCD2zgsmDwHyBC/B/XON4c5BpX+AVLv3XsxA9YKdH7KFCW7eMImJ5WUA9vD0V5m22yTm2Drsbx4L7w53QxPlvh5jxdblgbnakXUzpBHQ8w6+Q4qnpssmK1NBbCRh48RBtiunC/9OyPE/sMT2/CcN5xOVZDRsd1/UG/dPl9fZleOG35C8exZjiwPizW/3Z3N8KIbCh5s4GhWTOPwTov2GtFDkPirUJhHv5MGdt77XBLbNW/SPBuRm7w/EC5WyecN6oOGHpHVVScTBcV5zyURVNq/cg2z5oEN/xYidjf2LIq3x3cjZwsmOwT8A/bhe6YW/tg96tATgiUbS91Ao4DGgRtflFAv6tD9QAAklGAaUN4uSxJ7w9H0N5lJCQYGlKSmTwb2KYLGuFaNqgQflkbfGoOeR2vsXOJAZx0qA4xSfbiesyembmQ6s94gZK8sH3AtZlF2Wfmv7YXRqOhOZ53n96V2mWbcdwWoofFCc9rQoF5RinYtZnAoQ9L44zXnhmC0/2n27119MM6yD9KZTxo4VgD/DD/wIjQiHg=
