sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --install-ghc build
- stack exec hendleyhardgoods clean
- stack exec hendleyhardgoods build
cache:
  directories:
  - "$HOME/.stack"
deploy:
  provider: s3
  access_key_id: AKIAJOPJPECIU2VKXQIA
  secret_access_key: 
    secure: x7iJqtWzrx/vhnwmZjuT0etjymRM7xf1GOnruetd8fB/4FVGHhtp2xRbi8rWWZVfGeEP8OkKtm/g95MarWPIi0OpSUk4puuwljfxJw66xjazdFvcVaxPVBriFR6X0ld0iMsZsIld1WQvsdI+WSfW5Rw9pp0K3e85ApuEOp1J7jy9Hqap0GHANX1gMVZszbkQJZ8uSwOy5sKDmDVLjz9jQgTe+kNfQ2MEbfsZPoXexprUHU0hMZHGgdweW0eEMtCIuShcsARrZnjaXZL5jPsC497pLiXzitzBJzcShnOH+aIB0x2Eso2C5gm0waab+qiFdXpvN3oRLZEZymsNgyYIOUYXoMZZlJDqVCZbrSHkpFfod4rek83VeUi0ZGzIfOV12yxG6wBy2jZYU0SKNwRqfj+M8PpFPnlsUEWJ07nE4LxryE8P9rQfMG6LE+tLZfReP6GCxybmmuXAJ9h5CVuv4ssC5dj5zzVBX0NbXMxkskNQEvqHJBguae7LDRaq1tWFYaoL454QRxRN3WRD0aph4JxadQPmEDYZr3A/t9zTIfNZdClA+bSe7qE88uXizaYV5qwNVedHx51OQKgFfWhotlUCGGkIOqfinzdM21l0P1jf57WTB4lDzdbNn3LlzzXdW8ffu15iWnEtmXi4APWyBxA3VGVuZfdxyG4rKCORfFY=
  bucket: hendleyhardgoods.com
  local-dir: build
  acl: public_read
  region: us-west-1
  skip_cleanup: true
  on:
    repo: schell/hendleyhardgoods
    branch: master
